version: "3.7"

services:
  web_demo_hnm:
    build: .
    container_name: demo_hnm_web
    environment:
      - QDRANT_HOST=qdrant_demo_hnm
    depends_on:
      - qdrant_demo_hnm
    networks:
      - qdrant-net

  qdrant_demo_hnm:
    image: qdrant/qdrant:v0.7.0
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    networks:
      - qdrant-net

networks:
  qdrant-net:
    external:
      name: qdrant-net
